// <auto-generated />
using API_Labb4.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API_Labb4.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20230517133344_third mig")]
    partial class thirdmig
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("API_Labb4_ClassLibrary.Models.Interest", b =>
                {
                    b.Property<int>("InterestID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InterestID"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("InterestID");

                    b.ToTable("Interest");

                    b.HasData(
                        new
                        {
                            InterestID = 1,
                            Description = "Capturing moments throught pictures",
                            Title = "Photography"
                        },
                        new
                        {
                            InterestID = 2,
                            Description = "Exploring new places and new cultures",
                            Title = "Travel"
                        },
                        new
                        {
                            InterestID = 3,
                            Description = "Preparing and sharing delicious meals",
                            Title = "Cooking"
                        },
                        new
                        {
                            InterestID = 4,
                            Description = "Escaping the real world for some time",
                            Title = "Reading"
                        },
                        new
                        {
                            InterestID = 5,
                            Description = "Expressing creativity through colors and brushstrokes",
                            Title = "Painting"
                        },
                        new
                        {
                            InterestID = 6,
                            Description = "Crafting stories, poems, or articles to convey thoughts and emotions",
                            Title = "Writing"
                        },
                        new
                        {
                            InterestID = 7,
                            Description = "Engaging in physical activities to stay fit and competitive",
                            Title = "Sports"
                        },
                        new
                        {
                            InterestID = 8,
                            Description = "Cultivating plants and flowers to create beautiful outdoor spaces",
                            Title = "Gardening"
                        },
                        new
                        {
                            InterestID = 9,
                            Description = "Playing instruments or singing to create melodies and evoke emotions",
                            Title = "Music"
                        },
                        new
                        {
                            InterestID = 10,
                            Description = "Moving rhythmically to music, expressing oneself through body movements",
                            Title = "Dancing"
                        },
                        new
                        {
                            InterestID = 11,
                            Description = "Exploring natural landscapes on foot, enjoying scenic views and fresh air",
                            Title = "Hiking"
                        },
                        new
                        {
                            InterestID = 12,
                            Description = "Practicing mindfulness, flexibility, and relaxation through physical postures and breathing exercises",
                            Title = "Yoga"
                        });
                });

            modelBuilder.Entity("API_Labb4_ClassLibrary.Models.Link", b =>
                {
                    b.Property<int>("LinkID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LinkID"), 1L, 1);

                    b.Property<string>("LinkName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LinkURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LinkID");

                    b.ToTable("Link");

                    b.HasData(
                        new
                        {
                            LinkID = 1,
                            LinkName = "Instagram Profile",
                            LinkURL = "https://www.instagram.com"
                        },
                        new
                        {
                            LinkID = 2,
                            LinkName = "Lonely Planet Website",
                            LinkURL = "https://www.lonelyplanter.com"
                        },
                        new
                        {
                            LinkID = 3,
                            LinkName = "Food Website",
                            LinkURL = "https://www.foodnetwork.com"
                        },
                        new
                        {
                            LinkID = 4,
                            LinkName = "Goodreads",
                            LinkURL = "https://www.goodreads.com"
                        },
                        new
                        {
                            LinkID = 5,
                            LinkName = "Artists Network",
                            LinkURL = "https://www.artistsnetwork.com"
                        },
                        new
                        {
                            LinkID = 6,
                            LinkName = "Medium",
                            LinkURL = "https://medium.com"
                        },
                        new
                        {
                            LinkID = 7,
                            LinkName = "ESPN",
                            LinkURL = "https://www.espn.com"
                        },
                        new
                        {
                            LinkID = 8,
                            LinkName = "The Spruce",
                            LinkURL = "https://www.thespruce.com"
                        },
                        new
                        {
                            LinkID = 9,
                            LinkName = "Spotify",
                            LinkURL = "https://www.spotify.com"
                        },
                        new
                        {
                            LinkID = 10,
                            LinkName = "Dance Spirit",
                            LinkURL = "https://www.dancespirit.com"
                        });
                });

            modelBuilder.Entity("API_Labb4_ClassLibrary.Models.Person", b =>
                {
                    b.Property<int>("PersonID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PersonID"), 1L, 1);

                    b.Property<string>("PersonLName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PersonName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PersonID");

                    b.ToTable("Person");

                    b.HasData(
                        new
                        {
                            PersonID = 1,
                            PersonLName = "Smith",
                            PersonName = "John",
                            PhoneNumber = "555-123"
                        },
                        new
                        {
                            PersonID = 2,
                            PersonLName = "Doe",
                            PersonName = "Jane",
                            PhoneNumber = "555-678"
                        },
                        new
                        {
                            PersonID = 3,
                            PersonLName = "Johnsson",
                            PersonName = "David",
                            PhoneNumber = "555-345"
                        },
                        new
                        {
                            PersonID = 4,
                            PersonLName = "Johnson",
                            PersonName = "Emily",
                            PhoneNumber = "555-987"
                        },
                        new
                        {
                            PersonID = 5,
                            PersonLName = "Brown",
                            PersonName = "Michael",
                            PhoneNumber = "555-456"
                        },
                        new
                        {
                            PersonID = 6,
                            PersonLName = "Davis",
                            PersonName = "Olivia",
                            PhoneNumber = "555-789"
                        });
                });

            modelBuilder.Entity("API_Labb4_ClassLibrary.Models.PersonInterest", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<int>("InterestID")
                        .HasColumnType("int");

                    b.Property<int>("LinkID")
                        .HasColumnType("int");

                    b.Property<int>("PersonID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("InterestID");

                    b.HasIndex("LinkID")
                        .IsUnique();

                    b.HasIndex("PersonID");

                    b.ToTable("PersonInterest");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            InterestID = 1,
                            LinkID = 1,
                            PersonID = 1
                        },
                        new
                        {
                            ID = 2,
                            InterestID = 2,
                            LinkID = 2,
                            PersonID = 2
                        },
                        new
                        {
                            ID = 3,
                            InterestID = 3,
                            LinkID = 3,
                            PersonID = 3
                        });
                });

            modelBuilder.Entity("API_Labb4_ClassLibrary.Models.PersonInterest", b =>
                {
                    b.HasOne("API_Labb4_ClassLibrary.Models.Interest", "Interest")
                        .WithMany()
                        .HasForeignKey("InterestID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API_Labb4_ClassLibrary.Models.Link", "Link")
                        .WithOne("PersonInterest")
                        .HasForeignKey("API_Labb4_ClassLibrary.Models.PersonInterest", "LinkID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API_Labb4_ClassLibrary.Models.Person", "Person")
                        .WithMany()
                        .HasForeignKey("PersonID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Interest");

                    b.Navigation("Link");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("API_Labb4_ClassLibrary.Models.Link", b =>
                {
                    b.Navigation("PersonInterest")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
